name: memento_core

description: Core that contains abstracts and implementations of Memento features.

version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.4.0"
  
dependencies:
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  glow:
    git: https://github.com/Gierr7976/glow
    
dev_dependencies:
  flutter_test:
    sdk: flutter